---
- hosts: localhost
  gather_facts: yes
  vars:
    ami_id: "ami-026dea5602e368e96"
  module_defaults:
    group/aws:
      region: "us-east-2"
  tasks:
    - name: Provision Mike M5 ec2 instances
      ec2:
        key_name: AuburnKeyPair
        group: module5-rds-sg
        instance_type: t3.micro
        image: ami-026dea5602e368e96
        instance_tags:
          Name: Module5 Mike
          Module: 5
        wait: yes
        vpc_subnet_id: "{{ public_subnet1.subnet.id }}"
        assign_public_ip: yes
        exact_count: 1
        count_tag:
          Name: Module5 Mike
        user_data: "{{ lookup('file', '~/ansible/startup-scripts/start.sh') }}"

